<?xml version="1.0" encoding="utf-8"?><Database Name="QLCGP" Class="dulieuDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ASUS-A556UF-MOC;Initial Catalog=QLCGP;Integrated Security=True" SettingsObjectName="QuanLyCayGiaPha.Properties.Settings" SettingsPropertyName="QLCGPConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.GhiNhanThanhTich" Member="GhiNhanThanhTiches">
    <Type Name="GhiNhanThanhTich">
      <Column Name="MaTT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaTV" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="LoaiTT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayPS" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.KetThuc" Member="KetThucs">
    <Type Name="KetThuc">
      <Column Name="MaKT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaTV" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NguyenNhan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayGio" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DiaDiemMT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NguoiDung" Member="NguoiDungs">
    <Type Name="NguoiDung">
      <Column Name="TaiKhoan" Type="System.String" DbType="NChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="matkhau" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="ChucVu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThanhVien" Member="ThanhViens">
    <Type Name="ThanhVien">
      <Column Name="MaTV" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTenTVC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HoTenTVM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoaiQuanHe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayPhatSinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgheNghiep" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HinhAnh" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>